version: '3.8'

services:
  attendancedash_db:
    image: postgres:16
    container_name: attendancedashpro_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: attendancedash
    ports:
      - "5433:5432"
    volumes:
      - attendancedash_data:/var/lib/postgresql/data

volumes:
  attendancedash_data:
