from enum import Enum

class ClassType(str, Enum):
    LECTURE = "L"
    TUTORIAL = "T"
    PRACTICAL = "P"

class AttendanceStatus(str, Enum):
    ATTENDED = "Attended"
    MISSED = "Missed"
    PENDING = "Pending"

class EventType(str, Enum):
    EXTRA_LECTURE = "EXTRA_LECTURE"
    EXTRA_TUTORIAL = "EXTRA_TUTORIAL"
    EXTRA_PRACTICAL = "EXTRA_PRACTICAL"
    CLASS_CANCELLED = "CLASS_CANCELLED"
    SURPRISE_QUIZ = "SURPRISE_QUIZ"
    QUIZ_DAY = "QUIZ_DAY"
    PUBLIC_HOLIDAY = "PUBLIC_HOLIDAY"
    INSTITUTE_HOLIDAY = "INSTITUTE_HOLIDAY"
    WORKING_DAY_OVERRIDE = "WORKING_DAY_OVERRIDE"
    WORKING_SATURDAY = "WORKING_SATURDAY"
    EMERGENCY_CLOSURE = "EMERGENCY_CLOSURE"
    FESTIVAL_HOLIDAY = "FESTIVAL_HOLIDAY"
    SEMESTER_BREAK = "SEMESTER_BREAK"
    MID_SEMESTER_BREAK = "MID_SEMESTER_BREAK"

class UserRole(str, Enum):
    STUDENT = "STUDENT"
    ADMIN = "ADMIN"

class SubjectCategory(str, Enum):
    THEORY = "theory"
    LAB = "lab"
