"""Initial schema

Revision ID: 7117a007a0da
Revises: 
Create Date: 2026-08-12 18:38:16.984521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7117a007a0da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_sessions',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_sessions_name'), 'academic_sessions', ['name'], unique=True)
    op.create_table('quiz_cycles',
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_cycles_cycle_number'), 'quiz_cycles', ['cycle_number'], unique=True)
    op.create_table('eligibility_policies',
    sa.Column('quiz_cycle_id', sa.UUID(), nullable=False),
    sa.Column('lecture_threshold', sa.Float(), nullable=False),
    sa.Column('combined_threshold', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quiz_cycle_id'], ['quiz_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('semesters',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['academic_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sections',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('semester_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_name'), 'sections', ['name'], unique=True)
    op.create_table('subjects',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('THEORY', 'LAB', name='subjectcategory'), nullable=False),
    sa.Column('quiz_applicable', sa.Boolean(), nullable=False),
    sa.Column('attendance_applicable', sa.Boolean(), nullable=False),
    sa.Column('semester_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_code'), 'subjects', ['code'], unique=False)
    op.create_table('academic_events',
    sa.Column('event_type', sa.Enum('EXTRA_LECTURE', 'EXTRA_TUTORIAL', 'EXTRA_PRACTICAL', 'CLASS_CANCELLED', 'SURPRISE_QUIZ', 'QUIZ_DAY', 'PUBLIC_HOLIDAY', 'INSTITUTE_HOLIDAY', 'WORKING_DAY_OVERRIDE', 'WORKING_SATURDAY', 'EMERGENCY_CLOSURE', 'FESTIVAL_HOLIDAY', 'SEMESTER_BREAK', 'MID_SEMESTER_BREAK', name='eventtype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('class_type', sa.Enum('LECTURE', 'TUTORIAL', 'PRACTICAL', name='classtype'), nullable=True),
    sa.Column('is_working_day', sa.Boolean(), nullable=True),
    sa.Column('substitution_schedule_override', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laboratory_experiments',
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('experiment_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_schedules',
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('quiz_cycle_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('schedule_status', sa.Enum('SCHEDULED', 'UNRESOLVED', 'CANCELLED', name='schedulestatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quiz_cycle_id'], ['quiz_cycles.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timetable_entries',
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('class_type', sa.Enum('LECTURE', 'TUTORIAL', 'PRACTICAL', name='classtype'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('firebase_uid', sa.String(), nullable=False),
    sa.Column('roll_number', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_users_roll_number'), 'users', ['roll_number'], unique=True)
    op.create_table('class_sessions',
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('class_type', sa.Enum('LECTURE', 'TUTORIAL', 'PRACTICAL', name='classtype'), nullable=False),
    sa.Column('is_extra', sa.Boolean(), nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('timetable_entry_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['timetable_entry_id'], ['timetable_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laboratory_records',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('date_conducted', sa.Date(), nullable=True),
    sa.Column('signature_status', sa.Enum('PENDING', 'SIGNED', name='signaturestatus'), nullable=False),
    sa.Column('signed_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('marks', sa.Float(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['laboratory_experiments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'experiment_id', name='uq_user_experiment')
    )
    op.create_table('student_enrollments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_records',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('class_session_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ATTENDED', 'MISSED', 'PENDING', name='attendancestatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_session_id'], ['class_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'class_session_id', name='uq_user_class_session')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance_records')
    op.drop_table('student_enrollments')
    op.drop_table('laboratory_records')
    op.drop_table('class_sessions')
    op.drop_index(op.f('ix_users_roll_number'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_table('users')
    op.drop_table('timetable_entries')
    op.drop_table('quiz_schedules')
    op.drop_table('laboratory_experiments')
    op.drop_table('academic_events')
    op.drop_index(op.f('ix_subjects_code'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_sections_name'), table_name='sections')
    op.drop_table('sections')
    op.drop_table('semesters')
    op.drop_table('eligibility_policies')
    op.drop_index(op.f('ix_quiz_cycles_cycle_number'), table_name='quiz_cycles')
    op.drop_table('quiz_cycles')
    op.drop_index(op.f('ix_academic_sessions_name'), table_name='academic_sessions')
    op.drop_table('academic_sessions')
    # ### end Alembic commands ###
